/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "tuplas.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
initto_429005(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, Initto, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
settovarue_429005(int key, char *value1, int value2, double value3, int *clnt_res,  CLIENT *clnt)
{
	settovarue_429005_argument arg;
	arg.key = key;
	arg.value1 = value1;
	arg.value2 = value2;
	arg.value3 = value3;
	return (clnt_call (clnt, Settovarue, (xdrproc_t) xdr_settovarue_429005_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
gettovarue_429005(int key, struct Response *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, Gettovarue,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_Response, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modifuicvarue_429005(int key, char *value1, int value2, double value3, int *clnt_res,  CLIENT *clnt)
{
	modifuicvarue_429005_argument arg;
	arg.key = key;
	arg.value1 = value1;
	arg.value2 = value2;
	arg.value3 = value3;
	return (clnt_call (clnt, Modifuicvarue, (xdrproc_t) xdr_modifuicvarue_429005_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
deletto_429005(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, Deletto,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
existt_429005(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, Existt,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
copyvarue_429005(int key, int key2, int *clnt_res,  CLIENT *clnt)
{
	copyvarue_429005_argument arg;
	arg.key = key;
	arg.key2 = key2;
	return (clnt_call (clnt, Copyvarue, (xdrproc_t) xdr_copyvarue_429005_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
