//*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>

/*standard libraries*/

#include<string.h>
#include<stdlib.h>
#include<stdio.h>
#include<unistd.h>
#include<errno.h>

/*libraries for threads*/
#include <pthread.h>

#include "servidor.h"

#include "tuplas.h"

bbool_t
initto_429005_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result = real_init();
	retval = TRUE;
	return retval;
}

bool_t
settovarue_429005_svc(int key, char *value1, int value2, double value3, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	*result=real_set_value(key,value1,value2,value3);
	retval = TRUE;
	return retval;
}

bool_t
gettovarue_429005_svc(int *key, struct Response *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	int status;
	status=real_get_value(key,result.value1,&result.value2,&result.value3);
	if (status == -1){
        strcpy(result.value1, "NULL");
        result.value2 = 0;
        result.value3 = 0.0;
    }
	*key=status;
	retval = TRUE;
	return retval;
}

bool_t
modifuicvarue_429005_svc(int key, char *value1, int value2, double value3, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result=real_modify_value(key, value1, value2,value3);
	retval = TRUE;
	return retval;
}

bool_t
deletto_429005_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result=real_delete_key(key);
	retval = TRUE;
	return retval;
}

bool_t
existt_429005_svc(int key, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */

	*result=real_exist(key);
	retval = TRUE;
	return retval;
}


bool_t
copyvarue_429005_svc(int key, int key2, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	*result=real_copy_key(key,key2);
	retval = TRUE;
	return retval;
}

int
tuples_429005_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
