/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tuplas.h"

bool_t
xdr_Response (XDR *xdrs, Response *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->value, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_settovarue_429005_argument (XDR *xdrs, settovarue_429005_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_modifuicvarue_429005_argument (XDR *xdrs, modifuicvarue_429005_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value2))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_copyvarue_429005_argument (XDR *xdrs, copyvarue_429005_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->key2))
		 return FALSE;
	return TRUE;
}
