/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tuplas.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_initto_429005 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (initto_429005_svc(result, rqstp));
}

int
_settovarue_429005 (settovarue_429005_argument *argp, void *result, struct svc_req *rqstp)
{
	return (settovarue_429005_svc(argp->key, argp->value1, argp->value2, argp->value3, result, rqstp));
}

int
_gettovarue_429005 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (gettovarue_429005_svc(*argp, result, rqstp));
}

int
_modifuicvarue_429005 (modifuicvarue_429005_argument *argp, void *result, struct svc_req *rqstp)
{
	return (modifuicvarue_429005_svc(argp->key, argp->value1, argp->value2, argp->value3, result, rqstp));
}

int
_deletto_429005 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (deletto_429005_svc(*argp, result, rqstp));
}

int
_existt_429005 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (existt_429005_svc(*argp, result, rqstp));
}

int
_copyvarue_429005 (copyvarue_429005_argument *argp, void *result, struct svc_req *rqstp)
{
	return (copyvarue_429005_svc(argp->key, argp->key2, result, rqstp));
}

static void
tuples_429005(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		settovarue_429005_argument settovarue_429005_arg;
		int gettovarue_429005_arg;
		modifuicvarue_429005_argument modifuicvarue_429005_arg;
		int deletto_429005_arg;
		int existt_429005_arg;
		copyvarue_429005_argument copyvarue_429005_arg;
	} argument;
	union {
		int initto_429005_res;
		int settovarue_429005_res;
		struct Response gettovarue_429005_res;
		int modifuicvarue_429005_res;
		int deletto_429005_res;
		int existt_429005_res;
		int copyvarue_429005_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case Initto:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_initto_429005;
		break;

	case Settovarue:
		_xdr_argument = (xdrproc_t) xdr_settovarue_429005_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_settovarue_429005;
		break;

	case Gettovarue:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Response;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_gettovarue_429005;
		break;

	case Modifuicvarue:
		_xdr_argument = (xdrproc_t) xdr_modifuicvarue_429005_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_modifuicvarue_429005;
		break;

	case Deletto:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_deletto_429005;
		break;

	case Existt:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_existt_429005;
		break;

	case Copyvarue:
		_xdr_argument = (xdrproc_t) xdr_copyvarue_429005_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_copyvarue_429005;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!tuples_429005_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (tuples, TUPLESVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, tuples, TUPLESVER, tuples_429005, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (tuples, TUPLESVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, tuples, TUPLESVER, tuples_429005, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (tuples, TUPLESVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
