/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TUPLAS_H_RPCGEN
#define _TUPLAS_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Response {
	int key;
	char value[256];
	int value2;
	double value3;
};
typedef struct Response Response;

struct settovarue_429005_argument {
	int key;
	char *value1;
	int value2;
	double value3;
};
typedef struct settovarue_429005_argument settovarue_429005_argument;

struct modifuicvarue_429005_argument {
	int key;
	char *value1;
	int value2;
	double value3;
};
typedef struct modifuicvarue_429005_argument modifuicvarue_429005_argument;

struct copyvarue_429005_argument {
	int key;
	int key2;
};
typedef struct copyvarue_429005_argument copyvarue_429005_argument;

#define tuples 99
#define TUPLESVER 429005

#if defined(__STDC__) || defined(__cplusplus)
#define Initto 1
extern  enum clnt_stat initto_429005(int *, CLIENT *);
extern  bool_t initto_429005_svc(int *, struct svc_req *);
#define Settovarue 2
extern  enum clnt_stat settovarue_429005(int , char *, int , double , int *, CLIENT *);
extern  bool_t settovarue_429005_svc(int , char *, int , double , int *, struct svc_req *);
#define Gettovarue 3
extern  enum clnt_stat gettovarue_429005(int , struct Response *, CLIENT *);
extern  bool_t gettovarue_429005_svc(int , struct Response *, struct svc_req *);
#define Modifuicvarue 4
extern  enum clnt_stat modifuicvarue_429005(int , char *, int , double , int *, CLIENT *);
extern  bool_t modifuicvarue_429005_svc(int , char *, int , double , int *, struct svc_req *);
#define Deletto 5
extern  enum clnt_stat deletto_429005(int , int *, CLIENT *);
extern  bool_t deletto_429005_svc(int , int *, struct svc_req *);
#define Existt 6
extern  enum clnt_stat existt_429005(int , int *, CLIENT *);
extern  bool_t existt_429005_svc(int , int *, struct svc_req *);
#define Copyvarue 7
extern  enum clnt_stat copyvarue_429005(int , int , int *, CLIENT *);
extern  bool_t copyvarue_429005_svc(int , int , int *, struct svc_req *);
extern int tuples_429005_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Initto 1
extern  enum clnt_stat initto_429005();
extern  bool_t initto_429005_svc();
#define Settovarue 2
extern  enum clnt_stat settovarue_429005();
extern  bool_t settovarue_429005_svc();
#define Gettovarue 3
extern  enum clnt_stat gettovarue_429005();
extern  bool_t gettovarue_429005_svc();
#define Modifuicvarue 4
extern  enum clnt_stat modifuicvarue_429005();
extern  bool_t modifuicvarue_429005_svc();
#define Deletto 5
extern  enum clnt_stat deletto_429005();
extern  bool_t deletto_429005_svc();
#define Existt 6
extern  enum clnt_stat existt_429005();
extern  bool_t existt_429005_svc();
#define Copyvarue 7
extern  enum clnt_stat copyvarue_429005();
extern  bool_t copyvarue_429005_svc();
extern int tuples_429005_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Response (XDR *, Response*);
extern  bool_t xdr_settovarue_429005_argument (XDR *, settovarue_429005_argument*);
extern  bool_t xdr_modifuicvarue_429005_argument (XDR *, modifuicvarue_429005_argument*);
extern  bool_t xdr_copyvarue_429005_argument (XDR *, copyvarue_429005_argument*);

#else /* K&R C */
extern bool_t xdr_Response ();
extern bool_t xdr_settovarue_429005_argument ();
extern bool_t xdr_modifuicvarue_429005_argument ();
extern bool_t xdr_copyvarue_429005_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TUPLAS_H_RPCGEN */
